version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: wsgi.py
      FLASK_ENV: development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ../app:/app/app
      - ../wsgi.py:/app/wsgi.py
      - ../manage.py:/app/manage.py
      - ../docker/entrypoint.sh:/app/entrypoint.sh
      - ../migrations:/app/migrations
    depends_on:
      - postgres
      - neo4j

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
